"""rename_metadata_to_extra_metadata

Revision ID: b3eb42adbe57
Revises: 001
Create Date: 2026-04-08 23:15:40.538585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3eb42adbe57'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'BLOCKED', name='querystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_queries_created_at'), 'chat_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_queries_id'), 'chat_queries', ['id'], unique=False)
    op.create_index(op.f('ix_chat_queries_user_id'), 'chat_queries', ['user_id'], unique=False)
    op.create_table('query_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['chat_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_doc', 'query_documents', ['query_id', 'document_id'], unique=True)
    op.create_index(op.f('ix_query_documents_id'), 'query_documents', ['id'], unique=False)
    op.add_column('audit_logs', sa.Column('extra_metadata', sa.Text(), nullable=True))
    op.drop_column('audit_logs', 'metadata')
    op.create_index(op.f('ix_document_acl_id'), 'document_acl', ['id'], unique=False)
    op.drop_index('chunk_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_chunk_id', table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.drop_index('jti', table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'], unique=False)
    op.create_index('jti', 'revoked_tokens', ['jti'], unique=True)
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.create_index('ix_document_chunks_chunk_id', 'document_chunks', ['chunk_id'], unique=False)
    op.create_index('chunk_id', 'document_chunks', ['chunk_id'], unique=True)
    op.drop_index(op.f('ix_document_acl_id'), table_name='document_acl')
    op.add_column('audit_logs', sa.Column('metadata', mysql.TEXT(), nullable=True))
    op.drop_column('audit_logs', 'extra_metadata')
    op.drop_index(op.f('ix_query_documents_id'), table_name='query_documents')
    op.drop_index('idx_query_doc', table_name='query_documents')
    op.drop_table('query_documents')
    op.drop_index(op.f('ix_chat_queries_user_id'), table_name='chat_queries')
    op.drop_index(op.f('ix_chat_queries_id'), table_name='chat_queries')
    op.drop_index(op.f('ix_chat_queries_created_at'), table_name='chat_queries')
    op.drop_table('chat_queries')
    # ### end Alembic commands ###
